In [ ]:
import pandas as pd

In [ ]:
from os import access
mostly used for unstructred data to structured data as per need and as per action
unstrctured data:raw data--data without any specific dimension
                 has all possible info which as per need can be shifted to needed dimension---(parameters)
                 Human---all info
                                --->educational data:degree,score,result
                                --->health:states of organs,blood group,....
                                --->cloths:style,colors,size
                                ---->money:blance,turnover
structured data:data in rows and columns--->limited info ,loss of data,
                                        --->needed info direct access
                                        data base---info--row X columns
                                        lossy:as needed only kept
panda---*.csv     comma separated values---->act as table without any query language needed---No-SQL

In [ ]:
pandas---series(1D),dataframe(2D),3d(n dataframes)
    info of one type,rowsXcolumns,rowsXcolumnsX3:time
n series--->1 data frame------>n Data Frames--->1(time based data frame):Panel

In [ ]:
pip install pandas

In [ ]:
import pandas as pd #using pd shrtform for access

In [ ]:
#series--->made from list data structure
s=pd.Series([11,22,33,44,55])

In [ ]:
print(type(s))

<class 'pandas.core.series.Series'>

In [ ]:
print(s)#direct printable

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [ ]:
for item in s:#iteratable
    print(item)

11
22
33
44
55

In [ ]:
for i in range(len(s)):#indexed
    print(f"at s[{i}] we have:{s[i]}")

at s[0] we have:11
at s[1] we have:22
at s[2] we have:33
at s[3] we have:44
at s[4] we have:55

In [ ]:
l=[11,22,33]
l*3

[11, 22, 33, 11, 22, 33, 11, 22, 33]

In [ ]:
series directly operated at element level
print("s*3:",s*3)

s*3: 0     33
1     66
2     99
3    132
4    165
dtype: int64

In [ ]:
s[-1]

KeyError: -1

In [ ]:
min(s)

11

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving emp.csv to emp (2).csv

In [ ]:
import pandas as pd
df=pd.read_csv("emp.csv")
print(df)

            Name  Experience  Salary  Phone Number    Location
0   Aarav Sharma           5  750000    9876543210      Mumbai
1   Saanvi Patel           3  550000    9123456789   Bangalore
2   Vivaan Gupta           8  900000    9988776655       Delhi
3     Ananya Rao           4  620000    9234567890   Hyderabad
4    Arjun Mehta           6  800000    9345678901     Chennai
5     Isha Desai           2  450000    9467890123        Pune
6  Reyansh Kumar           7  850000    9123456781   Ahmedabad
7     Mira Singh           5  720000    9678901234      Jaipur
8   Aakash Verma           9  950000    9898765432     Kolkata
9     Kiara Nair           3  580000    9786543210  Coimbatore

In [ ]:
#single data/column  df.<NAME>
df.Name

0     Aarav Sharma
1     Saanvi Patel
2     Vivaan Gupta
3       Ananya Rao
4      Arjun Mehta
5       Isha Desai
6    Reyansh Kumar
7       Mira Singh
8     Aakash Verma
9       Kiara Nair
Name: Name, dtype: object

In [ ]:
df[['Name','Salary']]#mutiple column

            Name  Salary
0   Aarav Sharma  750000
1   Saanvi Patel  550000
2   Vivaan Gupta  900000
3     Ananya Rao  620000
4    Arjun Mehta  800000
5     Isha Desai  450000
6  Reyansh Kumar  850000
7     Mira Singh  720000
8   Aakash Verma  950000
9     Kiara Nair  580000

In [ ]:
df[['Location','Name','Salary']]#mutiple column

     Location           Name  Salary
0      Mumbai   Aarav Sharma  750000
1   Bangalore   Saanvi Patel  550000
2       Delhi   Vivaan Gupta  900000
3   Hyderabad     Ananya Rao  620000
4     Chennai    Arjun Mehta  800000
5        Pune     Isha Desai  450000
6   Ahmedabad  Reyansh Kumar  850000
7      Jaipur     Mira Singh  720000
8     Kolkata   Aakash Verma  950000
9  Coimbatore     Kiara Nair  580000

In [ ]:
df[['Salary']]*0.01

   Salary
0  7500.0
1  5500.0
2  9000.0
3  6200.0
4  8000.0
5  4500.0
6  8500.0
7  7200.0
8  9500.0
9  5800.0

In [ ]:
df['Tax']=df.Salary*0.01

In [ ]:
df

            Name  Experience  Salary  Phone Number    Location     Tax
0   Aarav Sharma           5  750000    9876543210      Mumbai  7500.0
1   Saanvi Patel           3  550000    9123456789   Bangalore  5500.0
2   Vivaan Gupta           8  900000    9988776655       Delhi  9000.0
3     Ananya Rao           4  620000    9234567890   Hyderabad  6200.0
4    Arjun Mehta           6  800000    9345678901     Chennai  8000.0
5     Isha Desai           2  450000    9467890123        Pune  4500.0
6  Reyansh Kumar           7  850000    9123456781   Ahmedabad  8500.0
7     Mira Singh           5  720000    9678901234      Jaipur  7200.0
8   Aakash Verma           9  950000    9898765432     Kolkata  9500.0
9     Kiara Nair           3  580000    9786543210  Coimbatore  5800.0

In [ ]:
#Net_Salary=Salary-Tax
df['Net_Salary']=df['Salary']-df['Tax']
print(df)

            Name  Experience  Salary  Phone Number    Location     Tax  \
0   Aarav Sharma           5  750000    9876543210      Mumbai  7500.0
1   Saanvi Patel           3  550000    9123456789   Bangalore  5500.0
2   Vivaan Gupta           8  900000    9988776655       Delhi  9000.0
3     Ananya Rao           4  620000    9234567890   Hyderabad  6200.0
4    Arjun Mehta           6  800000    9345678901     Chennai  8000.0
5     Isha Desai           2  450000    9467890123        Pune  4500.0
6  Reyansh Kumar           7  850000    9123456781   Ahmedabad  8500.0
7     Mira Singh           5  720000    9678901234      Jaipur  7200.0
8   Aakash Verma           9  950000    9898765432     Kolkata  9500.0
9     Kiara Nair           3  580000    9786543210  Coimbatore  5800.0

   Net_Salary
0    742500.0
1    544500.0
2    891000.0
3    613800.0
4    792000.0
5    445500.0
6    841500.0
7    712800.0
8    940500.0
9    574200.0

In [ ]:
len(df)

10

In [ ]:
#last 5 records/first 5 record
print(df.tail(2))
print(df.head(2))

           Name  Experience  Salary  Phone Number    Location     Tax  \
8  Aakash Verma           9  950000    9898765432     Kolkata  9500.0
9    Kiara Nair           3  580000    9786543210  Coimbatore  5800.0

   Net_Salary
8    940500.0
9    574200.0
           Name  Experience  Salary  Phone Number   Location     Tax  \
0  Aarav Sharma           5  750000    9876543210     Mumbai  7500.0
1  Saanvi Patel           3  550000    9123456789  Bangalore  5500.0

   Net_Salary
0    742500.0
1    544500.0

In [ ]:
df.tail(4)

,Name,Experience,Salary,Phone Number,Location,Tax,Net_Salary
6,Reyansh Kumar,7,850000,9123456781,Ahmedabad,8500.0,841500.0
7,Mira Singh,5,720000,9678901234,Jaipur,7200.0,712800.0
8,Aakash Verma,9,950000,9898765432,Kolkata,9500.0,940500.0
9,Kiara Nair,3,580000,9786543210,Coimbatore,5800.0,574200.0

In [ ]:
#list all columns
for column in df:
    print(column)

Name
Experience
Salary
Phone Number
Location
Tax
Net_Salary

In [ ]:
#list each record
for index in range(len(df)):
    print("-"*30)
    print(df.loc[index])

------------------------------
Name            Aarav Sharma
Experience                 5
Salary                750000
Phone Number      9876543210
Location              Mumbai
Tax                   7500.0
Net_Salary          742500.0
Name: 0, dtype: object
------------------------------
Name            Saanvi Patel
Experience                 3
Salary                550000
Phone Number      9123456789
Location           Bangalore
Tax                   5500.0
Net_Salary          544500.0
Name: 1, dtype: object
------------------------------
Name            Vivaan Gupta
Experience                 8
Salary                900000
Phone Number      9988776655
Location               Delhi
Tax                   9000.0
Net_Salary          891000.0
Name: 2, dtype: object
------------------------------
Name            Ananya Rao
Experience               4
Salary              620000
Phone Number    9234567890
Location         Hyderabad
Tax                 6200.0
Net_Salary        613800.0
Name: 3, dtype: object
------------------------------
Name            Arjun Mehta
Experience                6
Salary               800000
Phone Number     9345678901
Location            Chennai
Tax                  8000.0
Net_Salary         792000.0
Name: 4, dtype: object
------------------------------
Name            Isha Desai
Experience               2
Salary              450000
Phone Number    9467890123
Location              Pune
Tax                 4500.0
Net_Salary        445500.0
Name: 5, dtype: object
------------------------------
Name            Reyansh Kumar
Experience                  7
Salary                 850000
Phone Number       9123456781
Location            Ahmedabad
Tax                    8500.0
Net_Salary           841500.0
Name: 6, dtype: object
------------------------------
Name            Mira Singh
Experience               5
Salary              720000
Phone Number    9678901234
Location            Jaipur
Tax                 7200.0
Net_Salary        712800.0
Name: 7, dtype: object
------------------------------
Name            Aakash Verma
Experience                 9
Salary                950000
Phone Number      9898765432
Location             Kolkata
Tax                   9500.0
Net_Salary          940500.0
Name: 8, dtype: object
------------------------------
Name            Kiara Nair
Experience               3
Salary              580000
Phone Number    9786543210
Location        Coimbatore
Tax                 5800.0
Net_Salary        574200.0
Name: 9, dtype: object

In [ ]:
df.loc[::-1]#3 willbe included

,Name,Experience,Salary,Phone Number,Location,Tax,Net_Salary
9,Kiara Nair,3,580000,9786543210,Coimbatore,5800.0,574200.0
8,Aakash Verma,9,950000,9898765432,Kolkata,9500.0,940500.0
7,Mira Singh,5,720000,9678901234,Jaipur,7200.0,712800.0
6,Reyansh Kumar,7,850000,9123456781,Ahmedabad,8500.0,841500.0
5,Isha Desai,2,450000,9467890123,Pune,4500.0,445500.0
4,Arjun Mehta,6,800000,9345678901,Chennai,8000.0,792000.0
3,Ananya Rao,4,620000,9234567890,Hyderabad,6200.0,613800.0
2,Vivaan Gupta,8,900000,9988776655,Delhi,9000.0,891000.0
1,Saanvi Patel,3,550000,9123456789,Bangalore,5500.0,544500.0
0,Aarav Sharma,5,750000,9876543210,Mumbai,7500.0,742500.0

In [ ]:
df.Salary<600000

0    False
1     True
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9     True
Name: Salary, dtype: bool

In [ ]:
df[df.Salary<600000]

,Name,Experience,Salary,Phone Number,Location,Tax,Net_Salary
1,Saanvi Patel,3,550000,9123456789,Bangalore,5500.0,544500.0
5,Isha Desai,2,450000,9467890123,Pune,4500.0,445500.0
9,Kiara Nair,3,580000,9786543210,Coimbatore,5800.0,574200.0

In [ ]:
df[df.Experience>5]

,Name,Experience,Salary,Phone Number,Location,Tax,Net_Salary
2,Vivaan Gupta,8,900000,9988776655,Delhi,9000.0,891000.0
4,Arjun Mehta,6,800000,9345678901,Chennai,8000.0,792000.0
6,Reyansh Kumar,7,850000,9123456781,Ahmedabad,8500.0,841500.0
8,Aakash Verma,9,950000,9898765432,Kolkata,9500.0,940500.0

In [ ]:
df[(df.Salary>600000) & (df.Experience<5)]

         Name  Experience  Salary  Phone Number   Location     Tax  Net_Salary
3  Ananya Rao           4  620000    9234567890  Hyderabad  6200.0    613800.0

In [ ]:
df[df.Salary==max(df.Salary)]

           Name  Experience  Salary  Phone Number Location     Tax  Net_Salary
8  Aakash Verma           9  950000    9898765432  Kolkata  9500.0    940500.0

In [ ]:
df[df.Experience==min(df.Experience)]

         Name  Experience  Salary  Phone Number Location     Tax  Net_Salary
5  Isha Desai           2  450000    9467890123     Pune  4500.0    445500.0

In [ ]:
df[df.Salary<sum(df.Salary)/len(df)]

,Name,Experience,Salary,Phone Number,Location,Tax,Net_Salary
1,Saanvi Patel,3,550000,9123456789,Bangalore,5500.0,544500.0
3,Ananya Rao,4,620000,9234567890,Hyderabad,6200.0,613800.0
5,Isha Desai,2,450000,9467890123,Pune,4500.0,445500.0
9,Kiara Nair,3,580000,9786543210,Coimbatore,5800.0,574200.0

In [ ]:
new_df=pd.DataFrame({"Seat_no":[1,2,3,],"Name":["amar","chaman","taman"]})

In [ ]:
new_df

   Seat_no    Name
0        1    amar
1        2  chaman
2        3   taman

In [ ]:
new_df.insert(2,"gender",['m','m','m'])
            location,name,data

In [ ]:
new_df

   Seat_no    Name gender
0        1    amar      m
1        2  chaman      m
2        3   taman      m

In [ ]:
#create new dict with data
df_female=pd.DataFrame({"Seat_no":[4,5,6],"Name":["uma","seema","vilma"],"gender":["f","f","f"]})
print(df_female)
#append to dataframe .append()
new_df=pd.concat([df_female,new_df])

   Seat_no   Name gender
0        4    uma      f
1        5  seema      f
2        6  vilma      f

In [ ]:
print(new_df)

   Seat_no    Name gender
0        4     uma      f
1        5   seema      f
2        6   vilma      f
0        1    amar      m
1        2  chaman      m
2        3   taman      m

In [ ]:
new_df.sort_values(['Seat_no'])

   Seat_no    Name gender
0        1    amar      m
1        2  chaman      m
2        3   taman      m
0        4     uma      f
1        5   seema      f
2        6   vilma      f